#version: '3.8'
#
#services:
#  redis:
#    image: redis:latest
#    container_name: redis
#    ports:
#      - "6379:6379"
#    networks:
#      - my-network
#
#  app:
#    build: .
#    container_name: spring_boot_app
#    ports:
#      - "8080:8080"
#    depends_on:
#      - redis
#    environment:
#      - SPRING_DATA_REDIS_HOST=redis
#      - SPRING_DATA_REDIS_PORT=6379
#networks:
#  my-network:
#    driver: bridge